### ISSUE TITLE
Ajustar import no projeto

### ISSUE THREAD

**Issue by oliveiralex** [rmotaop/github-user-search#1]
Olá rmotaop,

Estou corrigindo o seu trabalho. O mesmo foi aceito, parabéns! Peço que você verifique pois na primeira vez que eu executei deu o seguinte erro:

`Module not found: Can't resolve './app.css' in `

Para funcionar eu tive que alterar o nome do import no arquivo App.tsx, para "import './App.css'".

Peço que você faça os ajustes assim que possível.

Abraço

**Comment by rmotaop** [comment]
Obrigado, ajuste efetuado.

**Comment by oliveiralex** [comment]
Obrigado!
